### ISSUE TITLE
Main Router Outlet

### ISSUE THREAD

**Issue by tessSnap** [sirajc/angular2-bs4-navbar#3]
Hello . During navigation in child views how do you ensure that components are displayed in the host child view's <router-outlet> instead of the one in app.component ?

**Comment by sirajc** [comment]
Chid views are loaded in the router-outlet of parent component. In this app HeroList and HeroDetail are loaded in the router outlet provided by HeroComponent.

Also, hero list and detail routes are children of hero route.

The above two play together and in rendering the view in correct place. This is handled by the router
